name: CI
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Target stage:'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      deploy:
        description: 'Deploy from this branch to the specified stage'
        type: boolean
        default: false
        required: true
        
concurrency:
  group: build-and-test
  cancel-in-progress: false
  
jobs:
  build:
    #if: ${{ inputs.deploy == true || github.ref == 'refs/heads/master'}} && inputs.stage == 'dev'
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.stage == 'dev' }}
        run: echo dev
      - if: ${{ inputs.stage == 'prod' }}
        run: echo prod
  #test:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - run: echo ${{github.ref}}
