name: CI
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Target stage:'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      deploy:
        description: 'Deploy from this branch to the specified stage'
        type: boolean
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: nc -zv -w 1 google.com 443
